### ISSUE TITLE
readme.md 可能需要更新下

### ISSUE THREAD

**Issue by uiwo** [xushanpei/vite_vue3_ts#1]
.eslintrc.js 配置那一段
rule出现了重复的配置项
'no-var': 'error',
'no-var': 'warn',

**Comment by xushanpei** [comment]
> .eslintrc.js 配置那一段 rule出现了重复的配置项 'no-var': 'error', 'no-var': 'warn',

感谢指正

**Comment by uiwo** [comment]
不谢不谢，刚开始看vue3 ts，你这个项目对我帮助非常大

**Comment by xushanpei** [comment]
> 

加微信: xsp_web_share 一起学习

**Comment by uiwo** [comment]
已加😎
